# Generated by Django 5.2.8 on 2025-11-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.productgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku_name', models.CharField(max_length=200)),
                ('product_customer_name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100)),
                ('erp_item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('minimum_order', models.IntegerField()),
                ('maximum_order', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.packaging')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productgroup')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='FreshStockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=120)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('inward_qty', models.DecimalField(decimal_places=3, help_text='Inward quantity (kgs)', max_digits=12)),
                ('total', models.DecimalField(decimal_places=3, help_text='Total (kgs)', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fresh_stock_ins', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('product', 'batch_number'), name='unique_product_batch_fresh')],
            },
        ),
        migrations.CreateModel(
            name='BananaGroupStockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=120)),
                ('offload_in_days', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity (units or kgs)', max_digits=12)),
                ('inward_quantity', models.DecimalField(decimal_places=3, help_text='Inward quantity (kgs)', max_digits=12)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_stock_ins', to='products.container')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_stock_ins', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('product', 'batch_number'), name='unique_product_batch_group')],
            },
        ),
    ]
