# Generated by Django 5.2.8 on 2025-11-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bananagroupstockin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='freshstockin',
            name='is_active',
        ),
    ]
