# Generated by Django 5.2.8 on 2025-11-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_bananagroupstockin_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bananagroupstockin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Banana Group Stock-In', 'verbose_name_plural': 'Banana Group Stock-In'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('id',), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ('id',), 'verbose_name': 'Container', 'verbose_name_plural': 'Containers'},
        ),
        migrations.AlterModelOptions(
            name='freshstockin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fresh Stock-In', 'verbose_name_plural': 'Fresh Stock-In'},
        ),
        migrations.AlterModelOptions(
            name='packaging',
            options={'ordering': ('id',), 'verbose_name': 'Packaging', 'verbose_name_plural': 'Packaging Types'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ('id',), 'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('id',), 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='product_group',
            new_name='product_group_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sku_name',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='freshstockin',
            name='batch_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='freshstockin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='freshstockin',
            name='inward_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='freshstockin',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fresh_stock_ins', to='products.product'),
        ),
        migrations.AlterField(
            model_name='freshstockin',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='maximum_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.packaging'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productgroup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
