# Generated by Django 5.2.8 on 2025-11-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_oo_stocktype_alter_freshstockin_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='stock_type',
        ),
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2025-11-28 00:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2025-11-28 00:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='container',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2025-11-28 00:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='packaging',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2025-11-28 00:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packaging',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2025-11-28 00:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2025-11-28 00:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='container_stockins', to='products.container'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.DeleteModel(
            name='OO',
        ),
        migrations.DeleteModel(
            name='StockType',
        ),
    ]
