# Generated by Django 5.2.8 on 2025-11-28 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_stockin_created_by_remove_stockin_stock_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stockins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockin',
            name='stock_type',
            field=models.CharField(choices=[('fresh product', 'fresh product'), ('warehouse transfer', 'warehouse transfer'), ('unsold', 'unsold')], default='fresh_product', max_length=50),
        ),
    ]
