# Generated by Django 5.2.8 on 2025-12-02 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stockin_created_by_stockin_stock_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='container_stockin', to='products.container'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_stockin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_stockin', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='stock_type',
            field=models.CharField(choices=[('fresh_product', 'fresh product'), ('warehouse_transfer', 'warehouse transfer'), ('unsold', 'unsold')], default='fresh_product', max_length=50),
        ),
    ]
