# Generated by Django 5.2.8 on 2025-12-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_brand_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_name_products', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_name_products', to='products.category'),
        ),
        migrations.AlterModelTable(
            name='brand',
            table='brand_name',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category_name',
        ),
        migrations.AlterModelTable(
            name='container',
            table='container',
        ),
        migrations.AlterModelTable(
            name='packaging',
            table='packaging',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productgroup',
            table='product_group',
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table='product_variant',
        ),
        migrations.AlterModelTable(
            name='stockin',
            table='stock_in',
        ),
    ]
