# Generated by Django 5.2.8 on 2025-12-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_brand_name_alter_product_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product_group_variant',
        ),
    ]
