# Generated by Django 5.2.8 on 2025-12-11 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='SurveyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('permissions', models.ManyToManyField(related_name='survey_forms', to='SurveyForm.permission')),
            ],
            options={
                'db_table': 'SurveyForm',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('date', 'Date'), ('number', 'Number'), ('mobile_number', 'Mobile Number'), ('single_choice', 'Single Choice'), ('multi_choice', 'Multiple Choice')], max_length=20)),
                ('mandatory', models.BooleanField(default=False)),
                ('default_hide', models.BooleanField(default=False)),
                ('use_for_analytics', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_form', to='SurveyForm.surveyform')),
            ],
            options={
                'db_table': 'SurveyQuestion',
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_question', to='SurveyForm.surveyquestion')),
            ],
            options={
                'db_table': 'SurveyOption',
            },
        ),
    ]
