# Generated by Django 5.2.8 on 2025-12-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
