# Generated by Django 5.2.8 on 2025-12-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyForm', '0002_alter_permission_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='SurveyPermission',
        ),
        migrations.AlterModelTable(
            name='surveypermission',
            table='survey_permission',
        ),
    ]
