# Generated by Django 5.2.8 on 2025-12-17 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyForm', '0003_rename_permission_surveypermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyform',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='surveyoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SurveyOption_question', to='SurveyForm.surveyquestion'),
        ),
        migrations.AlterField(
            model_name='surveypermission',
            name='key',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('tele_sales', 'Tele Sales'), ('trade_developer', 'Trade Developer')], max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='surveypermission',
            name='label',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SurveyQuestion_form', to='SurveyForm.surveyform'),
        ),
        migrations.AlterModelTable(
            name='surveyform',
            table='survey_forms',
        ),
        migrations.AlterModelTable(
            name='surveyoption',
            table='survey_options',
        ),
        migrations.AlterModelTable(
            name='surveypermission',
            table='survey_permissions',
        ),
        migrations.AlterModelTable(
            name='surveyquestion',
            table='survey_questions',
        ),
    ]
