# Generated by Django 5.2.8 on 2025-12-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyForm', '0004_remove_surveyform_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyform',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='SurveyForm_permissions', to='SurveyForm.surveypermission'),
        ),
        migrations.AlterField(
            model_name='surveypermission',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
