# Generated by Django 5.2.8 on 2025-12-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyForm', '0005_surveyform_permissions_alter_surveypermission_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyform',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='SurveyForm_permissions', to='SurveyForm.surveypermission'),
        ),
        migrations.AlterField(
            model_name='surveypermission',
            name='key',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('tele_sales', 'Tele Sales'), ('trade_developer', 'Trade Developer')], default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
