# Generated by Django 5.2.8 on 2025-12-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyForm', '0006_alter_surveyform_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveypermission',
            name='label',
        ),
        migrations.AlterField(
            model_name='surveypermission',
            name='key',
            field=models.CharField(choices=[('customer', 'Customer'), ('tele_sales', 'Tele Sales'), ('trade_developer', 'Trade Developer')], max_length=50),
        ),
    ]
